services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - webnet


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Nginx config files
      - ./staticfiles:/static             # Static files collected by Django
    depends_on:
      - chatapp
    networks:
      - webnet


  chatapp:
    build: .
    command: ["/bin/bash", "-c", "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 chatserver.asgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
