services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  chatapp:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 chatserver.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
